jobs:
- job: Build_Node
  timeoutInMinutes: 90
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    
  - task: PowerShell@2
    displayName: 'Build Node $(Version)'
    inputs:
      targetType: filePath
      filePath: './builders/build-node.ps1'
      arguments: '-Version $(Version) -Platform $(Platform) -Architecture $(Architecture)'

  - task: ArchiveFiles@2
    displayName: 'Archive artifact'
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)'
      archiveType: zip
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/node-$(Version)-$(Platform)-$(Architecture).zip'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: Node.js $(Version)'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/node-$(Version)-$(Platform)-$(Architecture).zip' 
      artifactName: 'node-$(Version)-$(Platform)-$(Architecture)'