name: $(date:yyyyMMdd)$(rev:.r)-Node.js-$(VERSION)
trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - master
  paths:
    exclude:
    - versions-manifest.json

stages:
- stage: Build_Node_Darwin
  dependsOn: []
  variables:
    Platform: darwin
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/build-job.yml

- stage: Test_Node_Darwin
  condition: succeeded()
  dependsOn: Build_Node_Darwin
  variables:
    VmImage: macOS-latest
    Platform: darwin
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/test-job.yml

- stage: Build_Node_Linux
  dependsOn: []
  variables:
    Platform: linux
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/build-job.yml

- stage: Test_Node_Linux
  condition: succeeded()
  dependsOn: Build_Node_Linux
  variables:
    VmImage: ubuntu-latest
    Platform: linux
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/test-job.yml

- stage: Build_Node_Windows
  dependsOn: []
  variables:
    Platform: win32
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/build-job.yml

- stage: Test_Node_Windows
  condition: succeeded()
  dependsOn: Build_Node_Windows
  variables:
    VmImage: windows-latest
    Platform: win32
    Architecture: x64
  jobs:
  - template: /azure-pipelines/templates/test-job.yml